display_name: FlClash Smart

icon: ./assets/images/icon.png

keywords:
  - FlClash Smart
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash Smart

categories:
  - Network

startup_notify: true

include: []
